#!/bin/bash

echo "Python boot-strap modules for machine wolf"

export LD_LIBRARY_PATH='/usr/lib64'
source /usr/share/Modules/init/bash

module purge
module load intel/15.0.5
module load openmpi/1.6.5
module use /usr/projects/climate/SHARED_CLIMATE/modulefiles/all
module load python/anaconda-2.7-cesm
module load nco/4.4.5
module load netcdf/4.4.0
module load hdf5/1.8.16

# prepend the virtualenv into the PATH

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/cesm-2.7/lib
